### ISSUE TITLE
java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by RoboMWM** [sanjay900/PortalStickNew#3]
Gonna assume you need to do some String.valueOf instead of a cast somewhere here. I'll make a PR if I get to it before you do.

Also, why does there need to be a diamond hoe in the offhand? (and it's also annoying to see it constantly being updated as I move, lol).

```
[20:12:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PortalStick v0.0.1-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.jar:git-Paper-925]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.jar:git-Paper-925]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-925]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-925]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.jar:git-Paper-925]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:899) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-925]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-925]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at net.tangentmc.portalStick.utils.Util.checkBlock(Util.java:90) ~[?:?]
	at net.tangentmc.portalStick.components.Portal.<init>(Portal.java:69) ~[?:?]
	at net.tangentmc.portalStick.components.PortalUser.setSecondary(PortalUser.java:82) ~[?:?]
	at net.tangentmc.portalStick.listeners.PlayerListener.playerInteract(PlayerListener.java:456) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor83.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.jar:git-Paper-925]
	... 18 more

**Comment by sanjay900** [comment]
Yeah, its not an issue if you have the right textures

**Comment by sanjay900** [comment]
There are a lot of diamonds hoes, I have a feeling you don't know half of
the plugins features at this point.

**Comment by RoboMWM** [comment]
Yes, I know, but I'm trying to just use the basic portal gun feature first (which is the primary thing I'm interested in as well, all the others are just extras to me)

Also, regarding the texture pack (yes, probably should be a separate issue...)

```
[20:12:45] [Server thread/INFO]: RoboMWM issued server command: /portal texture
[20:12:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'portal texture' in net.tangentmc.nmsUtils.utils.CommandBuilder$ReflectCommand(portal)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[patched_1.11.jar:git-Paper-925]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1373) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1178) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-925]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-925]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-925]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Resource pack URL cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.11.jar:git-Paper-925]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setResourcePack(CraftPlayer.java:1195) ~[patched_1.11.jar:git-Paper-925]
	at net.tangentmc.portalStick.commands.ToggleTextureCommand.execute(ToggleTextureCommand.java:25) ~[?:?]
	at net.tangentmc.portalStick.commands.BaseCommand.run(BaseCommand.java:66) ~[?:?]
	at net.tangentmc.portalStick.PortalStick.onCommand(PortalStick.java:122) ~[?:?]
	at net.tangentmc.nmsUtils.utils.CommandBuilder$ReflectCommand.execute(CommandBuilder.java:182) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.jar:git-Paper-925]
	... 14 more
```

**Comment by sanjay900** [comment]
It might actually be an issue with the default config

**Comment by RoboMWM** [comment]
Yea, forgot to mention I didn't clear config from old plugin.

**Comment by sanjay900** [comment]
That might actually cause problems, it was redone from scratch after all

**Comment by RoboMWM** [comment]
Anyways, as for original issue - I do have the all-blocks-allow-portals option enabled (in fact, I'd prefer the list be a blacklist vs. a whitelist). Seems I don't get this error when I set it to false. (Still getting the texture pack NPE despite deleting the portalstick folder and letting it regenerate config)
